name: C/C++ CI

on:
  push: ~
  pull_request: ~
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: configure
      run: chmod +x build.sh && chmod +x install.sh

    - name: update and install third-party
      run: sudo ./install.sh

    - name: build
      run: sudo ./build.sh