name: C/C++ CI

on:
  push: ~
  pull_request: ~
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2

    - name: configure
      run: chmod +x build.sh && chmod +x install.sh

    - name: update and install third-party
      run: sudo ./install.sh

    - name: build
      run: sudo ./build.sh

    - name: coverage
      run: codecov -t 8d1c8c84-247f-4c93-b694-77494affac62 -X gcov